name: Deploy GAS (pnpm)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dev deps
        run: pnpm i --frozen-lockfile=false

      # >>> usa os tokens do seu login local
      - name: Write clasp tokens
        shell: bash
        run: |
          mkdir -p ~/.clasprc && true
          echo "${{ secrets.CLASPRC_JSON }}" > ~/.clasprc.json

      # .clasp.json DEVE estar commitado com scriptId e rootDir
      - name: Push code to Apps Script
        run: pnpm exec clasp push

      - name: Create new version
        run: pnpm exec clasp version "CI ${GITHUB_SHA}"

      - name: Deploy Web App
        run: pnpm exec clasp deploy --description "CI deploy ${GITHUB_SHA}"

      - name: Show deployments (debug)
        run: pnpm exec clasp deployments || true