name: Deploy GAS (pnpm)

on:
  push:
    branches: [ main ]   # ajuste se usar outra branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dev deps
        run: pnpm i --frozen-lockfile=false

      # grava o token de login do clasp (precisa estar em CLASPRC_JSON)
      - name: Write clasp tokens
        shell: bash
        run: |
          cat > "$HOME/.clasprc.json" <<'JSON'
          ${{ secrets.CLASPRC_JSON }}
          JSON

      - name: Sanity check ~/.clasprc.json
        run: |
          node -e "const fs=require('fs');const p=process.env.HOME+'/.clasprc.json';const s=fs.readFileSync(p,'utf8');JSON.parse(s);console.log('OK .clasprc.json');"

      # .clasp.json precisa estar commitado com scriptId + rootDir
      - name: Push code to Apps Script
        run: pnpm exec clasp push

      - name: Create new version
        run: pnpm exec clasp version "CI ${GITHUB_SHA}"

      - name: Deploy Web App
        run: pnpm exec clasp deploy --description "CI deploy ${GITHUB_SHA}"

      - name: Show deployments (debug)
        run: pnpm exec clasp deployments || true
